var gf = [
{frage: "1 Welche Aussagen sind richtig?",
antworten: ["a) Die Feuerwehr ist eine gemeinnützige, der Nächstenhilfe dienende Einrichtung", "b) Die Feuerwehr ist ein gemeinnütziger Verein", "c) Die Feuerwehr ist ein Verein, ohne eigene Rechtspersönlichkeit", "d) Die Feuerwehr ist eine Einrichtung der Gemeinde", ],
loesungen: ['a', 'd', ],
},
{frage: "2 Welche Grundrechte können zur Erfüllung der Aufgaben der Feuerwehr nach § 2 des Feuerwehrgesetzes (FwG)Baden-Württemberg eingeschränkt werden?",
antworten: ["a) Freiheit der Person", "b) Meinungsfreiheit / Pressefreiheit", "c) Gleichheit vor dem Gesetz", "d) Versammlungsfreiheit", "e) Unverletzlichkeit der Wohnung", "f) Recht auf Eigentum", ],
loesungen: ['a', 'e', 'f', ],
},
{frage: "3 Welche Aufgabe hat der Feuerwehrausschuss (Abteilungsausschuss)entsprechend dem Feuerwehrgesetz (FwG)Baden-Württemberg und in welchen Zeitabständen ist er zu wählen?",
antworten: ["a) Jahresabschlussübung vorbereiten", "b) Beratung des Kommandanten", "c) Beschaffung von Feuerwehrfahrzeugen", "d) Feuerwehrangehörige bei fortgesetzter Nachlässigkeit im Dienst entlassen", "e) Kommandant unterstützen", "f) Feuerwehrsatzung erstellen", "g) Drei Jahre", "h) Fünf Jahre", ],
loesungen: ['b', 'e', 'h', ],
},
{frage: "4 Welche Aufgaben obliegen dem Land nach dem Feuerwehrgesetz Baden-Württemberg?",
antworten: ["a) Förderung der Aus- und Fortbildung", "b) Errichtung und Unterhaltung einer Landesfeuerwehrschule", "c) Lohnfortzahlung an Arbeitnehmer bei Arbeitsunfähigkeit in Folge eines Feuerwehreinsatzes", "d) Angehörige der Feuerwehr gegen Haftpflicht versichern", "e) Gemeinden bei der Beschaffung von Ausrüstung unterstützen", "f) Förderung der Normung und Forschung", "g) Für jeden Landkreis mindestens einen Kreisbrandmeister nach Anhörung der Kommandanten bestellen", ],
loesungen: ['a', 'b', 'e', 'f', ],
},
{frage: "5 Welches sind die Dienstpflichten der ehrenamtlich tätigen Angehörigen der Gemeindefeuerwehr?",
antworten: ["a) Am Dienst einschließlich der Aus- und Fortbildung regelmäßig und pünktlich teilnehmen", "b) Den dienstlichen Weisungen der Vorgesetzten nachkommen", "c) Sich im Dienst vorbildlich und kameradschaftlich verhalten", "d) Bei Alarm unverzüglich zur Einsatzstelle fahren", "e) Bei Alarm sich unverzüglich am Alarmplatz (Feuerwehrhaus)einzufinden", "f) Die technische Einsatzleitung übernehmen", "g) Hydrantenplan erstellen", ],
loesungen: ['a', 'b', 'c', 'e', ],
},
{frage: "6 Welche der Aussagen ist richtig?",
antworten: ["a) Feuerwehrangehörige sind bei der der Alarmfahrt mit dem eigenen Pkw zum Feuerwehrgerätehaus berechtigt, die §§ 35 und 38 der StVO in Anspruch zu nehmen, sie müssen nur dauernd hupen", "b) Feuerwehrangehörige müssen bei der Fahrt mit ihrem Pkw zum Feuerwehrhaus, auch bei einem Alarm, die allgemeinen Regeln der StVO einhalten", "c) Ein Anwesenheitsnachweis beim Einsatz- und Übungsdienst gehört zu einem geregelten Dienstbetrieb der Feuerwehr", "d) Die Gemeindefeuerwehr muss jährlich einen Dienstplan erstellen, der den Umfang und die Inhalte des Ausbildungs- und Übungsdienstes verbindlich festlegt", ],
loesungen: ['b', 'c', 'd', ],
},
{frage: "7 Wer entscheidet darüber, ob eine Katastrophe vorliegt?",
antworten: ["a) Der Feuerwehr-Einsatzleiter (Technischer Einsatzleiter)", "b) Die Ortspolizeibehörde", "c) Die Katastrophenschutzbehörde", "d) Das Lagezentrum im Regierungspräsidium", ],
loesungen: ['c', ],
},
{frage: "8 Welches sind die Katastrophenschutzbehörden nach dem Landeskatastrophenschutzgesetz?",
antworten: ["a) Die Berufsfeuerwehr eine Gemeinde", "b) Landratsämter und Bürgermeister der Stadtkreise", "c) Die Landesregierung", "d) Die Regierungspräsidien", "e) Das Innenministerium", ],
loesungen: ['b', 'd', 'e', ],
},
{frage: "9 Was versteht man unter dem Begriff \"untere Explosionsgrenze\"?",
antworten: ["a) Die Temperatur, bei der eine Explosion frühestens möglich ist", "b) Die Explosion eines Gas-Luft-Gemisches unter Erdgleiche", "c) Der niedrigste Sauerstoffgehalt (%)in der Luft, bei dem eine Explosion möglich ist", "d) Die niedrigste Konzentration des brennbaren Stoffes im Gemisch von Gasen, Dämpfen, Nebeln und/oder Stäuben, in dem sich nach dem Zünden ein Brennen gerade nicht mehr selbstständig fortpflanzen kann", ],
loesungen: ['d', ],
},
{frage: "10 Welche der aufgeführten Stoffe gehören zur Brandklasse A?",
antworten: ["a) Acetylen", "b) Aceton", "c) Ammoniak", "d) Autoreifen", "e) Baumwolle", "f) Holz (Hobelspäne)", "g) Bienenwachs", ],
loesungen: ['d', 'e', 'f', ],
},
{frage: "11 Bei welchem der aufgeführten Löschmittel ist der Stickeffekt als Hauptlöscheffekt zu betrachten?",
antworten: ["a) Wasser als Sprühstrahl", "b) Kohlenstoffdioxid", "c) Pulver für Brandklasse B und C", "d) Pulver für Brandklasse A, B und CO", "e) Luftschaum mit 75facher Verschäumung", ],
loesungen: ['b', 'e', ],
},
{frage: "12 Bei welchen Einsätzen ist Wasser als Löschmittel nicht anzuwenden?",
antworten: ["a) Schornsteinbrände", "b) bei Zersetzung von Düngemittel", "c) Metallbrände", "d) Heustockbrände", "e) Schwelbrände in Kellergeschossen", "f) Mineralölbrände", ],
loesungen: ['a', 'c', 'f', ],
},
{frage: "13 Wodurch ist eine Kraft gekennzeichnet?",
antworten: ["a) Größe der Kraft", "b) Geschwindigkeit der Kraft", "c) Richtung der Kraft", "d) Dauer der Kraftwirkung (Minuten / Sekunden)", "e) Angriffspunkt der Kraft", ],
loesungen: ['a', 'c', 'e', ],
},
{frage: "14 Welche Höchstlast L kann bei der vorliegenden Seilführung mit einem Mehrzweckzug Z 16 (Zugkraft 16 kN)gehoben werden?",
antworten: ["a) L = 1600 kg", "b) L = 3200 kg", "c) L = 4800 kg", "d) L = 6400 kg", ],
loesungen: ['b', ],
bild: "gf14.png",
},
{frage: "15 Für welchen Fahrbereich (km)oder Betrieb (h)fest eingebauter Aggregate muss der Kraftstoff bei Feuerwehrfahrzeugen mindestens ausreichend sein?",
antworten: ["a) 200 km oder 2 h", "b) 300 km oder 3 h", "c) 300 km oder 4 h", "d) 400 km oder 4 h", ],
loesungen: ['c', ],
},
{frage: "16 Welche Feuerwehrpumpen gehören nach Norm zu einem Löschgruppenfahrzeug LF 10?",
antworten: ["a) FPN 10/750", "b) FPN 10/1000", "c) TUP 3-1,5", "d) TP 8/1", ],
loesungen: ['b', ],
},
{frage: "17 Welchen Inhalt muss der eingebaute Löschwasserbehälter bei einem Löschgruppenfahrzeug LF 20 nach Norm mindestens haben?",
antworten: ["a) 800 Liter", "b) 1200 Liter", "c) 1600 Liter", "d) 2500 Liter", ],
loesungen: ['c', ],
},
{frage: "18 Wie reagiert ein Gruppenführer auf die Lagemeldung eines Angriffstrupps, wenn dieser meldet, er habe beim Vorgehen zur Brandbekämpfung in einem Raum Fässer mit brennbarer Flüssigkeit gefunden? Der Gruppenführer weist den Angriffstrupp an:",
antworten: ["a) Die Fässer heraus zu tragen", "b) Die Gefahrensymbole zu beschreiben", "c) Den Zustand der Fässer zu beschreiben", "d) Die Fässer zu kühlen", "e) Die Fässer abzulöschen", "f) An den Fässern nicht vorbeigehen", ],
loesungen: ['b', 'c', 'f', ],
},
{frage: "19 Wann ist an Brandstellen mit gefährlichen Konzentrationen von Kohlenstoffmonoxid CO zu rechnen?",
antworten: ["a) Nach einer Explosion", "b) Bei Bränden in geschlossenen Räumen bei mangelnder Luftzufuhr", "c) Bei Schwelbränden der Brandklasse A", "d) Bei Bränden der Brandklasse C", ],
loesungen: ['b', 'c', ],
},
{frage: "20 Welche der aufgeführten Atemgifte wirken durch Reiz- und Ätzwirkung schädigend auf den Menschen?",
antworten: ["a) Kohlenstoffdioxid", "b) Blausäure und Dämpfe von Methylalkohol", "c) Chlor und Säuredämpfe", "d) Nitrose Gase", "e) Stickstoff und Methan", ],
loesungen: ['c', 'd', ],
},
{frage: "21 In welchen der farblich gekennzeichneten Druckgasflaschen befinden sich brennbare Gase? In Klammer ( )ältere Kennzeichnung.",
antworten: ["a) Blaue Flaschen mit zwei weißen Kreisen auf der Flaschenschulter", "b) Kastanienbraune Flasche (gelb)", "c) Grüne Flasche", "d) Rote Flasche", "e) Graue Flasche", "f) Graue Flasche mit roter Gasflaschenschulter", ],
loesungen: ['b', 'd', 'f', ],
},
{frage: "22 Eine Acetylengasflasche ist längere Zeit der Brandwärme ausgesetzt. Was müssen Sie beachten?",
antworten: ["a) Eine weitere Erwärmung kann zu einem Druckgefäßzerknall führen", "b) Flasche muss aus geschützter Stellung fortlaufend gekühlt werden", "c) Nach dem Abkühlen kann sich die Flasche wieder von selbst erwärmen", "d) Flasche muss mindestens 24 Stunden nach Erreichen der normalen Temperatur an einem sicheren Ort gelagert und kontrolliert, notfalls weiterhin gekühlt werden", "e) Flasche kann nach dem Abkühlen zur weiteren Benutzung verwendet werden", "f) Flasche muss von der Feuerwehr gekennzeichnet und zum Füllwerk gebracht werden", "g) Flasche muss gekennzeichnet, an Füllwerk übergeben und von diesem überprüft werden", ],
loesungen: ['a', 'b', 'c', 'd', 'g', ],
},
{frage: "23 Bei welcher Art der Wärmeübertragung wird kein Übertragungsmedium benötigt?",
antworten: ["a) Wärmeströmung", "b) Wärmestrahlung", "c) Wärmeleitung", ],
loesungen: ['b', ],
},
{frage: "24 Welche Treibmittel werden in Feuerlöschern verwendet und welche Arten von tragbaren Feuerlöschern gibt es?",
antworten: ["a) Luft, Helium, Kohlenstoffdioxid", "b) Propan, Butan", "c) Flüssigkeitsbrandlöscher", "d) Aufladelöscher", "e) Dauerdrucklöscher", "f) Gaslöscher", "g) Giftlöscher", "h) Schlaglöscher","i) Pulverlöscher", ],
loesungen: ['a', 'd', 'e', 'f', 'i', ],
},
{frage: "25 Welche Löschmittel werden in tragbaren Feuerlöschern eingesetzt?",
antworten: ["a) Wasser mit Zusätzen", "b) Graugussspäne", "c) D-Löschpulver", "d) Schaumlöschmittel", "e) BC-Löschpulver", "f) ABC-Löschpulver", "g) Kohlenstoffdioxid", "h) Feiner Sand","i) Schweröl", "j) Wasser" ],
loesungen: ['a', 'c', 'd', 'e', 'f', 'g', 'j', ],
},
{frage: "26 Welche Vorteile hat ein Trinkwasserleitungsnetz, das als Ringleitungssystem ausgelegt ist?",
antworten: ["a) Es bilden sich in den Rohrleitungen weniger Ablagerungen", "b) Kurze Abschaltstrecken bei Rohrbruch", "c) Geringere Bau- und Unterhaltungskosten als bei einem Verästelungssystem", "d) Hydranten fließen von zwei Seiten Wasser zu", ],
loesungen: ['a', 'b', 'd', ],
},
{frage: "27 Nach welcher Faustformel errechnet sich der Abstand (m)von Verstärkerpumpen?",
antworten: ["a) Abstand = (Ausgangsdruck / Druckverlust)* 100", "b) Abstand = (Gesamtförderdruck / Druckverlust)* 100", "c) Abstand = (verfügbarer Druck / Druckverlust)* 100", ],
loesungen: ['c', ],
},
{frage: "28 In welcher maximalen Entfernung von einem Hydranten kann ein Löschfahrzeug aufgestellt werden, ohne dass Gefahr besteht, den notwendigen Pumpeneingangsdruck zu unterschreiten? (Wasserdruck am Standrohr: 5,4 bar, Förderstrom Q = 800 Liter/Minute, Reibungsverlust 1,3 bar / 100 Meter, verfügbare Wassermenge am Standrohr: 1200 Liter / Minute)",
antworten: ["a) 250 Meter", "b) 300 Meter", "c) 320 Meter", ],
loesungen: ['b', ],
},
{frage: "29 Wie viel Wasser (Liter/Minute)liefert ein Unterflurhydrant bei \"normalem\" Druckverhältnis im Rohrleitungsnetz?",
antworten: ["a) Nennweite (mm)der Anschlussleitung x 7-10", "b) Nennweite (mm)der Anschlussleitung x 12-15", "c) Nennweite (mm)der Anschlussleitung x 15-17", ],
loesungen: ['a', ],
},
{frage: "30 Welche Aufgaben muss der Wachhabende im Feuersicherheitswachdienst vor Beginn einer Veranstaltung wahrnehmen?",
antworten: ["a) Kontrolle der Rettungswege", "b) Einweisung der Sicherheitsposten", "c) Durchführung ordnungsdienstlicher Tätigkeiten", "d) Überprüfung der Alarmierungsmöglichkeiten", ],
loesungen: ['a', 'b', 'd', ],
},
{frage: "31 Welcher Baustoffklasse und welcher bauaufsichtlichen Benennung (nach DIN 4102)müssen Dekorationsmaterialien in Versammlungsräumen mindestens entsprechen?",
antworten: ["a) B1", "b) Normal entflammbar", "c) Schwer entflammbar", "d) F 30", ],
loesungen: ['a', 'c', ],
},
{frage: "32 Welche der nachfolgenden Bedingungen muss erfüllt sein, damit die Standsicherheit eines Gebäudes gewährleistet ist?",
antworten: ["a) Brandverhütungsschau muss durchgeführt sein", "b) Brandausbreitung in baulichen Anlagen richtig abschätzen", "c) Am Gebäude wirkende Kräfte müssen im Gleichgewicht sein", ],
loesungen: ['c', ],
},
{frage: "33 Welche baulichen Einrichtungen und Geräte können bei Gebäuden als Rettungsweg(Erster und zweiter Rettungsweg)angesehen werden?",
antworten: ["a) Notwendige Treppen", "b) Tragbare Leitern", "c) Fluchthauben", "d) Aufzüge", "e) Drehleitern", ],
loesungen: ['a', 'b', 'e', ],
},
{frage: "34 Welche bauaufsichtliche Benennung steht für die Feuerwiderstandsklasse F 30-B (nach DIN 4102)eines Bauteils?",
antworten: ["a) Feuerbeständig", "b) Feuerhemmend", "c) Nicht brennbar", "d) Schwer entflammbar", ],
loesungen: ['b', ],
},
{frage: "35 Welche der aufgeführten Tätigkeiten gehören zu den lebensrettenden Sofortmaßnahmen?",
antworten: ["a) Verkehrssicherung, Verkehrsregelung", "b) Knochenbrüche schienen", "c) Wiederbelebung, Atemspende", "d) Lagerung und Schockbekämpfung", "e) Anschrift und Name des Verletzten notieren", ],
loesungen: ['c', 'd', ],
},
{frage: "36 Welche Maßnahmen müssen eventuell durchgeführt werden, um die Vitalfunktionen einer verletzten Person aufrechtzuerhalten und/oder wieder herzustellen?",
antworten: ["a) Blutstillung", "b) Warmes Getränk verabreichen", "c) Injektion vorbereiten", "d) Lagerung", "e) Wärmeerhaltung", "f) Überwachung von Puls und Blutdruck", "g) Überwachung von Atmung und Bewusstseinslage", "h) Notruf veranlassen","i) Verletzten über Unfallhergang befragen" ],
loesungen: ['a', 'd', 'e', 'f', 'g', ],
},
{frage: "37 Welche Anzeigen deuten auf einen Schock hin?",
antworten: ["a) Durstgefühl", "b) Starke Kopfschmerzen", "c) Frieren, Zittern", "d) Blasse, kalte und feuchte Haut", "e) Starke Blutungen", "f) Auffallende Unruhe", "g) Schneller und schwächer werdender Puls", "h) Tiefer Schlaf","i) Auffallende Heiterkeit","j) Großes Mitteilungsbedürfniss" ],
loesungen: ['c', 'd', 'e', 'f', 'g', 'j', ],
},
{frage: "38 Welche Stelle auf der UTM-Karte wird durch die Koordinate 372378 bestimmt?",
antworten: ["a) Stelle A", "b) Stelle B", ],
loesungen: ['a', ],
bild: "gf38.png",
},
{frage: "39 Was ist beim Retten von hilflosen Personen aus Schächten zu beachten?",
antworten: ["a) Schacht mit Sauerstoff anreichern", "b) Retter mit Atemschutzgerät und Feuerwehrleine ausrüsten", "c) Person mit Feuerwehrleine oder Rettungsgurt sichern", ],
loesungen: ['b', 'c', ],
},
{frage: "40 Warum gibt es Feuerwehr-Einsatzpläne?",
antworten: ["a) Damit sich der Bürgermeister über die Einsatzfähigkeit seiner Feuerwehr informieren kann", "b) Damit sich der Einsatzleiter bei der Anfahrt über eventuelle Gefahren und das mögliche Vorgehen informieren kann", "c) Damit der Kreisbrandmeister die Einsatzleitung übernehmen kann", ],
loesungen: ['b', ],
},
{frage: "41 Kreuzen Sie die drei Tätigkeiten an, die der nach einem Alarm zuerst am Feuerwehrhaus eintreffende Feuerwehrangehörige vorrangig zu erledigen hat!",
antworten: ["a) Fahrzeugmotor warm laufen lassen", "b) Seine Ausrüstung holen und überprüfen", "c) Mit der Leitstelle Verbindung aufnehmen", "d) Kreisbrandmeister verständigen", "e) Einsatzauftrag von der Leitstelle erfragen", "f) Einsatzauftrag der Leitstelle wiederholen und eventuell aufschreiben", ],
loesungen: ['c', 'e', 'f', ],
},
{frage: "42 Wie fordern Sie als Gruppenführer in der Regel die Unterstützung anderer Feuerwehren oder Dienststellen bei einem Einsatz an?",
antworten: ["a) Direkt über Telefon", "b) Nur über die Leistelle", "c) Direkt über Funk", ],
loesungen: ['b', ],
},
{frage: "43 Welche Begriffe muss ein Befehl enthalten?",
antworten: ["a) Einheit", "b) Lage", "c) Hydranten", "d) Auftrag", "e) Ort, Zeit, Wetter", "f) Mittel", "g) Ziel", "h) Weg", "i) Schadenstelle" ],
loesungen: ['a', 'd', 'f', 'g', 'h', ],
},
{frage: "44 Wer entscheidet an der Einsatzstelle vorrangig über medizinische Maßnahmen am Verletzten?",
antworten: ["a) Technischer Einsatzleiter", "b) Bürgermeister", "c) Betriebsleiter beziehungsweise Werksdirektor", "d) Notarzt", "e) Kommandant", "f) Sicherheitsbeauftragte", ],
loesungen: ['d', ],
},
{frage: "45 Welche nachfolgenden Grundsätze sind im Sprechfunkverkehr zu beachten?",
antworten: ["a) Höflichkeitsformeln unterlassen", "b) Personennamen und Amtsbezeichnungen dürfen nicht genannt werden", "c) Teilnehmer mit \"Sie\" anreden", "d) Strenge Funkdisziplin einhalten", "e) Abkürzungen benutzen, damit Funkzeit kurz ist", "f) Eigennamen und schwer verständliche Worte buchstabieren", "g) Zahlen unverwechselbar aussprechen", "h) Deutlich und laut sprechen ohne Pausen", ],
loesungen: ['a', 'c', 'd', 'f', 'g', ],
},
{frage: "46 Verkehrsarten sind von den technischen Möglichkeiten der Funkgeräte abhängige Verfahren des Nachrichtenaustausches im Sprechfunkverkehr. Wie werden sie unterschieden?",
antworten: ["a) Wechselverkehr", "b) Richtungsverkehr", "c) Kreisverkehr", "d) Sternverkehr", "e) Gegenverkehr", "f) Bedingter Gegenverkehr", "g) Linienverkehr", ],
loesungen: ['a', 'b', 'e', 'f', ],
},
{frage: "47 Welche Aussage ist richtig?",
antworten: ["a) \"Einfach-Nachrichten\" werden in der Reihenfolge ihres Eingangs abgefertigt", "b) \"Sofort-Nachrichten\" müssen in der Reihenfolge ihres Eingangs jedoch vor \"Einfach-Nachrichten\" abgefertigt werden", "c) \"Gespräche\" sollen stichwortartig vorgefertigt sein und von der Gegenstelle niedergeschrieben beziehungsweise aufgezeichnet werden", "d) Das \"Gespräch\" ist ein formloser, unmittelbarer Informationsaustausch", "e) Der \"Spruch\" ist eine formgebundene, schriftlich festgelegte Nachricht", ],
loesungen: ['a', 'b', 'd', 'e', ],
},
{frage: "48 Eine orangenfarbige Warntafel zeigt die Gefahrnummer 856. Was liegt vor?",
antworten: ["a) Ätzender Stoff, brandfördernd und giftig", "b) Giftiger Stoff, brandfördernd und ätzend", "c) Oxidierend wirkender Stoff, giftig und ätzend", ],
loesungen: ['a', ],
},
{frage: "49 Eine orangenfarbige Warntafel zeigt die Gefahrnummer X 423. Was liegt vor?",
antworten: ["a) Entzündbarer fester Stoff, der mit Wasser gefährlich reagiert, wobei brennbare Gase entweichen", "b) Leicht entzündbare Flüssigkeit, mit Wasser gefährlich reagierend, dabei entweicht Gas", "c) Fester Stoff, leicht entzündbar, bei Berührung mit Wasser entweicht Gas", ],
loesungen: ['a', ],
},
{frage: "50 Im \"Hommel\" sehen Sie für einen Stoff im Gefahrendiamant im blauen Feld eine \"3\". Was bedeutet dies?",
antworten: ["a) Starke Reaktionsgefahr", "b) Vollschutzanzug erforderlich", "c) Sicherheitszone von mindestens 30 Meter bilden", "d) Stoff ist \"schwer entflammbar\"", "e) Gesundheitsgefahr", ],
loesungen: ['b', 'e', ],
},
{frage: "51 Eine Gaswolke (ätzende Gase)bildet sich im Freien aufgrund eines Lecks. Was tun Sie zuerst um die Bevölkerung zu schützen?",
antworten: ["a) Räumung der unmittelbar beaufschlagten Gebäude", "b) Leck abdichten, damit nichts mehr austritt", "c) Gaswolke mit Wasser eingrenzen beziehungsweise niederschlagen", ],
loesungen: ['c', ],
},
{frage: "52 Meldung Verkehrsunfall! Sie kommen mit einem Löschgruppenfahrzeug LF 10 und Ihrer Löschgruppe an die Einsatzstelle. Ihre Erkundung hat ergeben, dass keine Person im unmittelbaren Bereich gefährdet ist. Auf einem kleinen Lastkraftwagen (drei Tonnen)liegen zerstörte Behälter (60 Liter). Die Kennzeichnung der Behälter nach Gefahrstoff-Verordnung (GefStoffV)ist ätzend. Welche Maßnahmen veranlassen Sie?",
antworten: ["a) Einsatzstelle großräumig (50 Meter)absichern", "b) Gase mit Sprühstrahl unter Atemschutz niederschlagen", "c) Lagemeldung abgeben und Gerätewagen Gefahrgut anfordern, Kreisbrandmeister verständigen", "d) Lagemeldung abgeben und Rüstwagen anfordern, Transportfirma verständigen und Ersatzfahrzeug anfordern", "e) Ausgelaufene Flüssigkeit mit viel Wasser (Verdünnungseffekt)ins Kanalrohr spülen", ],
loesungen: ['a', 'b', 'c', ],
},
{frage: "53 Welches Gefährlichkeitsmerkmal kann einem Stoff zugeordnet werden?",
antworten: ["a) Sehr giftig", "b) Ekelhaft riechend / spontan reagierend", "c) Brandfördernd", "d) Krebserzeugend", "e) Explosionsgefährlich", ],
loesungen: ['a', 'c', 'd', 'e', ],
},
{frage: "54 Woran erkennt man, ob ein unbekannter Stoff giftig ist?",
antworten: ["a) Die Giftigkeit ist nicht ohne weiteres erkennbar", "b) Durch den Einsatz von Prüfröhrchen", "c) Mit Indikator-Papier (pH-Papier)", ],
loesungen: ['a', ],
},
{frage: "55 Die Dekontamination durch die Feuerwehr (Dekon)ist die Grobreinigung von Einsatzkräften einschließlich ihrer Schutzkleidung, von anderen Personen sowie von Geräten. Welche Aussage ist richtig?",
antworten: ["a) Der Dekon-Platz muss in spätestens 15 Minuten betriebsbereit sein", "b) Dekon-Stufe I = Notdekontamination von Personen", "c) Dekon-Stufe II = Standard-Dekontamination", "d) Dekon-Stufe III = Erweiterte Dekontamination im ABC-Einsatz", "e) Ein Dekon-Platz ist bei jedem ABC-Einsatz der Gefahrengruppe II und III einzurichten und abzugrenzen", ],
loesungen: ['a', 'b', 'c', 'd', 'e', ],
},
{frage: "56 Was bedeutet die Abkürzung \"TRGS\"?",
antworten: ["a) Technische Regeln für Gefahrstoffe", "b) Transport-Richtlinie für Gerätewagen-Säure", "c) Technisches Regelwerk für Gase und Säuren", ],
loesungen: ['a', ],
},
{frage: "57 Welche Aussage für Erdgas ist richtig?",
antworten: ["a) Erdgas ist leichter als Luft", "b) Erdgas ist gut riechbar", "c) Erdgas ist eingeatmet ein Blutgift", ],
loesungen: ['a', ],
},
{frage: "58 Welche grundsätzlichen Schutzmaßnahmen sind beim Einsatz mit radioaktiven Stoffen zu beachten?",
antworten: ["a) Abstand halten (groß)", "b) Aufenthaltsdauer kurz", "c) Abschirmung ausnutzen", "d) Kontamination vermeiden", "e) Inkorporation vermeiden", "f) Radioaktiven Stoff mit viel Wasser kühlen", "g) Radioaktiven Stoff aufnehmen", ],
loesungen: ['a', 'b', 'c', 'd', 'e', ],
},
{frage: "59 Welcher Abstand ist bis zur Festlegung der Absperrgrenze für nicht unmittelbar am Einsatz beteiligte Einsatzkräfte bei Unfällen mit radioaktiven Stoffen vom Schadensobjekt einzuhalten?",
antworten: ["a) 10 Meter", "b) 25 Meter", "c) 50 Meter", ],
loesungen: ['c', ],
},
{frage: "60 Bereiche mit ABC-Gefahrstoffen werden bei der Einsatzvorbereitung entsprechend den auszuführenden Maßnahmen in drei Gefahrengruppen eingeteilt. Welche Zuordnung ist richtig?",
antworten: ["a) Gefahrengruppe I - Bereiche, in denen die Einsatzkräfte nur mit Sonderausrüstung und unter besonderer Überwachung und Dekontamination/Hygiene tätig werden dürfen", "b) Gefahrengruppe II - Bereiche, in denen die Einsatzkräfte ohne Sonderausrüstung tätig werden dürfen. Zur Vermeidung einer Inkorporation soll jedoch Atemschutz getragen werden", "c) Gefahrengruppe III - Bereiche, in denen Einsatzkräfte nur mit Sonderausrüstung und unter besonderer Überwachung und Dekontamination/Hygiene tätig werden dürfen und deren Eigenart die Anwesenheit einer fachkundigen Person notwendig macht, die während des Einsatzes die entstehende Gefährdung und die anzuwendenden Schutzmaßnahmen beurteilen kann", ],
loesungen: ['c', ],
},
];
