var masch = [
{frage: "1 Auf was muss für die Betriebssicherheit an einem Feuerwehrfahrzeug geachtet werden?",
antworten: ["a) Wasser", "b) Motorenöl", "c) Beladung vollständig", "d) Reifenluftdruck", "e) Kraftstoff", "f) Funkausrüstung", "g) Elektrische Anlage", ],
loesungen: ['a', 'b', 'd', 'e', 'g', ],
},
{frage: "2 Wie groß soll der Elektrodenabstand bei der Zündkerze im Motor der Tragkraftspritze mit VW-Industriemotor sein und in welcher Stellung hat der Kraftstoffhahn nach beendetem Einsatz zu stehen?",
antworten: ["a) 0,6 bis 0,7 mm", "b) 0,4 mm", "c) Unter 0,2 mm", "d) Auf", "e) Zu", ],
loesungen: ['b', 'd', ],
},
{frage: "3 Auf was muss bei der Überprüfung der Verkehrssicherheit geachtet werden?",
antworten: ["a) Bremsen", "b) Beleuchtung", "c) Bereifung", "d) Beladung", "e) Nebenantrieb", "f) Lenkung", "g) Signal", "h) Spiegel", "i) Scheibenwischer", "j) Kraftstoff"],
loesungen: ['a', 'b', 'c', 'd', 'f', 'g', 'h', 'i', ],
},
{frage: "4 Welche der nachfolgenden Feuerwehr-Dienstvorschriften (FwDV)geben Hinweise auf die Aufgaben des Maschinisten?",
antworten: ["a) FwDV 3 ? Einheiten im Lösch- und Hilfeleistungseinsatz", "b) FwDV 500 ? Einheiten im ABC-Einsatz", "c) FwDV 10 ? Die tragbaren Leitern", "d) FwDV 810.3 ? Sprechfunkdienst", "e) FwDV 2 ? Ausbildung der Freiwilligen Feuerwehren", ],
loesungen: ['a', 'c', 'e', ],
},
{frage: "5 Was hat der Maschinist gemäß den Feuerwehr-Dienstvorschriften und den Richtlinien zur Durchführung der Leistungsübungen beim Einsatz in der Gruppe bei offener Wasserentnahme zu tun?",
antworten: ["a) Er hilft den Trupps beim Entnehmen der Geräte", "b) Er legt Kupplungsschlüssel (falls erforderlich)Saugkorb, Saugschutzkorb sowie Halte- und Ventilleine bereit", "c) Er kuppelt den Saugkorb an die Saugleitung an", "d) Er kuppelt die Schlauchleitung an die Pumpe an und bedient die Pumpe", "e) Er schlägt die Ventilleine im Bedienbereich der Pumpe und die Halteleine an einem festen Punkt an", ],
loesungen: ['a', 'b', 'd', 'e', ],
},
{frage: "6 Welche Wasserentnahmestellen erfordern ein Ansaugen des Wassers?",
antworten: ["a) Schachthydrant", "b) Überflurhydrant", "c) Unterflurhydrant", "d) Löschteich", "e) Unterirdischer Löschwasserbehälter", "f) Löschwasserbrunnen S", ],
loesungen: ['d', 'e', 'f', ],
},
{frage: "7 Welche Einflüsse führen dazu, dass die theoretische Saughöhe von 10,33 Meter nicht erreicht werden kann?",
antworten: ["a) Luftdruck unter dem Normaldruck", "b) Für das Fließen des Wassers im Saugschlauch wird Druck benötigt", "c) Reibungs- und Strömungsverluste", "d) Wasser ist schwerer als Luft", "e) Entlüftungseinrichtungen erzeugen kein 100%iges Vakuum", ],
loesungen: ['a', 'b', 'c', 'e', ],
},
{frage: "8 Mit welchem Knoten wird die Halte- und Ventilleine entsprechend der Richtlinie zur Durchführung der Leistungsübungen an den Festpunkten angebracht?",
antworten: ["a) Doppelschlinge", "b) Mastwurf", "c) Zimmermannsschlag", "d) Schotstich", "e) Ankerstich", ],
loesungen: ['b', ],
},
{frage: "9 Welchen Ausgangsdruck soll der Maschinist in der Regel an der Feuerlöschkreiselpumpe einhalten?",
antworten: ["a) Fünf bis sechs bar bei kurzer Entfernung zur Einsatzstelle", "b) Acht bar bei Wasserförderung über lange Wege", "c) Acht bis zehn bar bei Erzeugung von Schwerschaum", ],
loesungen: ['a', 'b', 'c', ],
},
{frage: "10 Löschwasserbrunnen sind künstlich angelegte Entnahmestellen für Löschwasser aus dem",
antworten: ["a) Eine Stunde", "b) Drei Stunden", "c) Gesamtdauer des Einsatzes", ],
loesungen: ['b', ],
},
{frage: "11 Was bedeutet bei einer Feuerlöschkreiselpumpe die 1. Ziffer in der Bezeichnung \"FPN 10/1000\"?",
antworten: ["a) Der Nennförderstrom ist 1000 Liter/Minute", "b) Der Nennförderdruck ist 10 bar", "c) Die Förderleistung ist 10 Kilowatt", ],
loesungen: ['b', ],
},
{frage: "12 Welche Aussage ist richtig?",
antworten: ["a) Die geodätische Saughöhe kann direkt am Eingangsmanometer der der Feuerlöschkreiselpumpe während der Wasserförderung abgelesen werden", "b) Die geodätische Saughöhe ist der Höhenunterschied in Meter zwischen Pumpenmitte und saugseitigem Wasserspiegel", "c) Das Maß der geodätischen Saughöhe ist für den Förderstrom ohne Einfluss", ],
loesungen: ['b', ],
},
{frage: "13 Welche Pumpenwellenabdichtung ist während des Betriebes nachstellbar?",
antworten: ["a) Radialdichtringe", "b) Stopfbuchsenpackung", "c) Gleitringdichtung", ],
loesungen: ['b', ],
},
{frage: "14 Welche der nachfolgenden Feuerwehrpumpen sind genormt?",
antworten: ["a) FPN 40/250", "b) FP 8/8", "c) FPN 10/750", "d) FPN 15/2000", "e) FP 24/8", "f) FP 32/8", "g) LP 24/3", "h) TUP 3-1,5","i) TP 4/1","j) TTP 8/1/8" ],
loesungen: ['a', 'c', 'd', 'h', 'i', 'j', ],
},
{frage: "15 Welche Bedingungen müssen beim 1. Garantiepunkt einer Feuerlöschkreiselpumpe FPN 15/1000 erfüllt werden?",
antworten: ["a) Der Nennförderdruck muss mindestens 15 bar betragen", "b) Der Nennförderstrom muss mindestens 1000 Liter/Minute sein", "c) Die Nenndrehzahl darf hierbei max. ± 5% abweichen", "d) Die geodätische Saughöhe muss 3,0 Meter betragen", "e) Die geodätische Saughöhe muss 7,5 Meter betragen", ],
loesungen: ['a', 'b', 'c', 'd', ],
},
{frage: "16 Was bewirkt Kavitation (Hohlsog)in einer Feuerlöschkreiselpumpe?",
antworten: ["a) In der Feuerlöschkreiselpumpe bilden sich so hohe Drücke, dass das Gehäuse schlagartig auseinander bricht", "b) Es bilden sich Dampfblasen in der Flüssigkeit, der Förderstrom kann nicht mehr erhöht werden", "c) Beim Zerfall der Dampfblasen wird der Werkstoff des Laufrades zerstört", ],
loesungen: ['b', 'c', ],
},
{frage: "17 Welche Entlüftungseinrichtungen sind Strahlapparate?",
antworten: ["a) Wasserstrahlpumpe", "b) Trockenring-Entlüftungspumpe", "c) Gasstrahler einstufig", "d) Gasstrahler zweistufig", ],
loesungen: ['c', 'd', ],
},
{frage: "18 Welche Möglichkeiten bestehen, wenn der Eingangsmanometer beim Ansaugen keinen negativen Druck anzeigt?",
antworten: ["a) Ausgangsventil der Feuerlöschkreiselpumpe ist offen", "b) Die Feuerlöschkreiselpumpe oder die Saugleitung ist undicht", "c) Das Schutzsieb am Saugkorb ist verstopft", "d) Das Rückschlagorgan sitzt im Saugkorb fest", "e) Der Saugkorb liegt teilweise außerhalb des Wassers", ],
loesungen: ['a', 'b', 'e', ],
},
{frage: "19 Was geschieht in der Feuerlöschkreiselpumpe, wenn der Wasserspaltring beschädigt ist?",
antworten: ["a) In der Feuerlöschkreiselpumpe entsteht ein Wasserkreislauf von der Druckseite zur Saugseite", "b) In der Feuerlöschkreiselpumpe entsteht ein Wasserkreislauf von der Saugseite zur Druckseite", "c) Beim Hydrantenbetrieb wird der Förderstrom größer, weil zusätzlich Wasser zu den Druckausgängen gelangen kann, dafür wird bei Saugbetrieb der Förderstrom geringer", "d) Durch den Wasserkreislauf in der Feuerlöschkreiselpumpe wird der Schließdruck geringer", ],
loesungen: ['a', 'd', ],
},
{frage: "20 Sie bedienen an der Brandstelle eine Feuerlöschkreiselpumpe FPN 10/1000 und halten einen Ausgangsdruck von fünf bis sechs bar. Es ist zu Nachlöscharbeiten - für Sie nicht sichtbar - noch ein C-Rohr in Stellung. Wasserentnahme: offenes Gewässer, Geodätische Saughöhe sechs Meter. Auf was müssen Sie achten?",
antworten: ["a) Dass der Druck konstant bleibt", "b) Weil die Feuerlöschkreiselpumpe nicht ausgelastet ist, brauchen Sie ihr keine besondere Aufmerksamkeit zu schenken. Sie können deshalb bei der Zurücknahme der nicht mehr benötigten Geräte behilflich sein", "c) Das Pumpengehäuse von Zeit zu Zeit mit der Hand auf Temperatur überprüfen. Notfalls freien Druckausgang etwas öffnen der Verbindungsleitung zum eingebauten Löschwasserbehälter etwas öffnen", ],
loesungen: ['a', 'c', ],
},
{frage: "21 Was bedeutet \"Kavitation\" beim Fördern von Wasser mit einer Feuerlöschkreiselpumpe?",
antworten: ["a) Zerstörung des Laufrades", "b) Zerstörung des Wasserspaltringes", "c) Bildung von Wasserdampfbläschen", ],
loesungen: ['a', 'c', ],
},
{frage: "22 An welchen äußeren Merkmalen erkennen Sie den Unterschied zwischen einer einstufigen und einer zweistufigen Feuerlöschkreiselpumpe?",
antworten: ["a) An der Zahl der Druckausgänge", "b) Am Typenschild (Nenndrehzahl)", "c) An der Form des Pumpengehäuses", "d) Am angegebenen Schließdruck", ],
loesungen: ['b', 'c', ],
},
{frage: "23 Die Heckpumpe vom Löschgruppenfahrzeug LF 10 ist an der Brandstelle im Einsatz. Die Wasserversorgung erfolgt über das Sammelstück vom Hydranten. Weil die Entnahme von Löschwasser aus der Versorgungsleitung unzureichend ist, wird mittels einer Tragkraftspritze PFPN 10/1000 Wasser aus einem in 200 Meter entfernten Teich entnommen. Frage: Darf die Zubringerleitung von der PFPN 10/1000 an das Sammelstück der Heckpumpe angeschlossen werden?",
antworten: ["a) Ja, weil Teichwasser wegen der Rückschlagklappe im Sammelstück nicht zum Hydranten gelangen kann", "b) Nein, weil Bakterien ins Rohrnetz der Wasserversorgung gelangen können", "c) Nur wenn der Druck des Rohrleitungsnetzes größer ist als der Druck in der Zubringerleitung von der PFPN 10/1000", "d) Nur wenn der Druck des Rohrleitungsnetzes niedriger ist als der Druck in der Zubringerleitung von der PFPN 10/1000", ],
loesungen: ['b', ],
},
{frage: "24 Welche Ursachen sind denkbar, wenn die geodätische Saughöhe ein Meter beträgt, das Eingangsmanometer - 0,6 bar anzeigt und trotz Vollgas keine Anzeige am Ausgangsmanometer erfolgt?",
antworten: ["a) Schutzsieb des Saugkorbs verstopft", "b) Saugkorb liegt teilweise außerhalb der Wasseroberfläche", "c) Schutzsieb am Pumpeneingang verstopft", "d) Rückschlagorgan im Saugkorb fehlt", "e) Förderstrom sehr groß", ],
loesungen: ['a', 'c', 'e', ],
},
{frage: "25 Welche wichtigen Bauteile sind an Feuerlöschkreiselpumpen vorhanden?",
antworten: ["a) Kupplung", "b) Gehäuse mit Gehäusedeckel", "c) Kurbelwelle", "d) Kolben und Ventile", "e) Armaturen und Bedienungseinrichtungen", "f) Entlüftungseinrichtung", "g) Laufrad (Laufräder)", "h) Messinstrumente","i) Schutzhaube" ],
loesungen: ['b', 'e', 'f', 'g', 'h', ],
},
{frage: "26 Was besagt der Begriff \"Kavitation\"?",
antworten: ["a) Geräuschbildung in der Feuerlöschkreiselpumpe ab vier Meter Saughöhe", "b) Fremdkörper (Flugsand o.ä.)im Löschwasser", "c) Bildung und Zerstörung von dampfgefühlten Hohlräumen in Flüssigkeiten", ],
loesungen: ['c', ],
},
{frage: "27 Welche der aufgeführten Armaturen legt der Maschinist bereit beziehungsweise schließt er an?",
antworten: ["a) Standrohr", "b) Saugkorb", "c) Sammelstück", "d) Druckbegrenzungsventil", "e) Verteiler", ],
loesungen: ['b', 'c', ],
},
{frage: "28 Worauf muss der Maschinist bei der Löschwasserförderung über lange Strecken achten?",
antworten: ["a) Verkehrsbehinderungen beachten", "b) Verkehrsbehinderungen so gering wie möglich zulassen", "c) Reserveschläuche und Ersatz-Feuerlöschkreiselpumpe bereithalten", "d) Nachrichtenübermittlung sicherstellen", "e) Förderleitung langsam füllen und auf angeordneten Druck gehen", "f) An der Verstärker-Feuerlöschkreiselpumpe freien Druckausgang öffnen, damit Luft aus der Schlauchleitung entweichen kann", "g) Dass der Förderdruck von acht bar eingehalten wird", "h) Bei Temperaturen unter 0o C stets für fließendes Wasser sorgen","i) Förderleitung beaufsichtigen","j) Dass Schlauchbrücken verlegt werden" ],
loesungen: ['e', 'f', 'g', 'h', ],
},
{frage: "29 Wie viel mm Abstand müssen zwischen Masse und Mittel-Elektrode bei Zündkerzen von Tragkraftspritzen PFPN 10/1000 vorhanden sein?",
antworten: ["a) Entsprechend der Betriebs- beziehungsweise Bedienungsanleitung", "b) Zehn Millimeter", "c) Acht Millimeter", ],
loesungen: ['a', ],
},
{frage: "30 Auf was muss bei der Überprüfung der Verkehrssicherheit an einem Feuerwehrfahrzeug geachtet werden?",
antworten: ["a) Beladung, Verriegelung der Schubfächer/Geräte", "b) Signal-Warnanlage", "c) Bereifung, Profiltiefe", ],
loesungen: ['a', 'b', 'c', ],
},
{frage: "31 Was muss vor der Prüfung der Leistungswerte (Garantie-Punkte)einer Feuerlöschkreiselpumpe durchgeführt werden?",
antworten: ["a) Geodätische Saughöhe muss überprüft werden", "b) Ölstand überprüfen", "c) Kraftstoffinhalt überprüfen", ],
loesungen: ['a', ],
},
{frage: "32 Kreuzen Sie die Entlüftungseinrichtungen an, die verdrängungstechnisch wirken!",
antworten: ["a) Flüssigkeitsring-Entlüftungseinrichtung", "b) Doppel-Freikolben-Entlüftungseinrichtung", "c) Trockenring-Entlüftungseinrichtung", "d) Gasstrahler (einstufig)-Entlüftungseinrichtung", "e) Gasstrahler (zweistufig)-Entlüftungseinrichtung", ],
loesungen: ['a', 'b', 'c', ],
},
{frage: "33 Wann darf die Feuerwehr Sonderrechte im Straßenverkehr in Anspruch nehmen?",
antworten: ["a) Bei allen Einsätzen", "b) Wenn der Einsatzleiter es anordnet", "c) Wenn Menschenleben in Gefahr sind", "d) Zur Erfüllung hoheitlicher Aufgaben, wenn höchste Eile dringend geboten ist", ],
loesungen: ['c', 'd', ],
},
{frage: "34 Bei einem Löschfahrzeug fällt die Entlüftungseinrichtung aus, weil die Auspuffanlage defekt ist. Welche Entlüftungseinrichtung hat das Fahrzeug?",
antworten: ["a) Flüssigkeitsring-Entlüftungseinrichtung", "b) Trockenring-Entlüftungseinrichtung", "c) Gasstrahler-Entlüftungseinrichtung", ],
loesungen: ['c', ],
},
{frage: "35 Zur Überprüfung der Einsatzbereitschaft einer Feuerlöschkreiselpumpe müssen Trockensaugproben gemacht werden. Wie oft soll dies geschehen?",
antworten: ["a) Mindestens einmal im Jahr", "b) Mindestens einmal im Monat", "c) Nach jedem Einsatz und jeder Übung", ],
loesungen: ['b', 'c', ],
},
{frage: "36 Was tut man, wenn die grüne Kontrollleuchte einer Tragkraftspritze PFPN 10-1000 mit VW-Industriemotor während des Pumpenbetriebes plötzlich erlischt?",
antworten: ["a) Motor abstellen, Ursache überprüfen und beseitigen, Pumpe in Betrieb nehmen, Einsatzleiter verständigen", "b) Motordrehzahl etwas zurück nehmen, optisch prüfen, ob Keilriemen noch Gebläserad und Lichtmaschine antreibt, wenn ja, Wasserförderung nicht unterbrechen, da nur eine elektrische Störung vorliegt. Einsatzleiter verständigen", ],
loesungen: ['b', ],
},
{frage: "37 Warum müssen während des Betriebes alle Blindkupplungen an den Druckausgängen einer Feuerlöschkreiselpumpe angenommen werden?",
antworten: ["a) Weil der Druck in der Pumpe sonst zu groß würde", "b) Weil sich zwischen dem Absperrorgan und der Blindkupplung ein Druck aufbauen könnte", "c) Weil sonst beim späteren Abnehmen der Blindkupplungen erhöhte Unfallgefahr besteht", ],
loesungen: ['b', 'c', ],
},
{frage: "38 In welcher Stellung soll sich die Kupplung einer Tragkraftspritze PFPN 10/1000 befinden, wenn sie im Fahrzeug gelagert ist?",
antworten: ["a) Betrieb", "b) Saugen", "c) Kupplung ein", "d) Kupplung aus", ],
loesungen: ['a', 'c', ],
},
{frage: "39 Wie berechnet man überschlägig den Kraftstoffverbrauch bei einem Löschgruppenfahrzeug während des Einsatzes der Pumpe, wenn die Tankuhr defekt ist?",
antworten: ["a) Eine Betriebsstunde der Feuerlöschkreiselpumpe entspricht etwa 60 km Fahrleistung", "b) Eine Betriebsstunde der Feuerlöschkreiselpumpe entspricht etwa 100 km Fahrleistung", ],
loesungen: ['a', ],
},
{frage: "40 Nach einem zweistündigen Einsatz an der Tragkraftspritze PFPN 10/1000 soll der Maschinist abgelöst werden. Worauf hat er zu achten, bevor er von der PFPN 10/1000 weggeht?",
antworten: ["a) Dass die Tragkraftspritze PFPN 10/1000 nur in stillstehendem Zustand übergeben wird", "b) Dass ausreichend Kraftstoff vorhanden ist", "c) Dass er den Ablösenden einweist", ],
loesungen: ['b', 'c', ],
},
{frage: "41 Während des Einsatzes einer Feuerlöschkreiselpumpe bleibt plötzlich der Antriebsmotor stehen. Welche Ursachen sind denkbar?",
antworten: ["a) Motor und Motorenöl wurden zu heiß", "b) Vergaser beziehungsweise Einspritzpumpe defekt", "c) Kraftstoffmangel", ],
loesungen: ['b', 'c', ],
},
{frage: "42 Der statische beziehungsweise dynamische Prüfdruck beträgt bei den Feuerlöschkreiselpumpen FPN 10/1000",
antworten: ["a) 15 bar bei stehender, 22,5 bar bei laufender Pumpe", "b) 16 bar bei stehender, 24,0 bar bei laufender Pumpe", ],
loesungen: ['a', ],
},
{frage: "43 Welche Feuerwehrpumpen dürfen zum Fördern von Heizöl extra leicht verwendet werden?",
antworten: ["a) Handmembranpumpe", "b) Tragkraftspritze", "c) Feuerlöschkreiselpumpe", "d) Umfüllpumpe TUP 3-1,5 ex geschützt", "e) tragbare Tauchpumpe mit Elektromotor TP 4-1", "f) Lenz-Kreiselpumpe", ],
loesungen: ['a', 'd', ],
},
{frage: "44 Welche Tätigkeiten gehören zu den Aufgaben des Maschinisten nach der Feuerwehr-Dienstvorschrift FwDV 3 \"Einheiten im Lösch- und Hilfeleistungseinsatz\"?",
antworten: ["a) Bedienung der Feuerlöschkreiselpumpe", "b) Fahren des Löschfahrzeugs", "c) Absichern der Einsatzstelle", "d) Mithilfe bei der Entnahme von Geräten aus dem Löschfahrzeug", "e) Bedienung von Sonderaggregaten", "f) Anschließen der Schlauchleitungen an die Feuerlöschkreiselpumpe", "g) Bereitlegen von Kupplungsschlüsseln (falls erforderlich), Saugkorb, Saugschutzkorb, Halte- und Ventilleine bei offener Wasserentnahme", "h) Standrohr in Stellung bringen bei Wasserentnahme aus dem Rohrnetz", ],
loesungen: ['a', 'b', 'd', 'e', 'f', 'g', ],
},
{frage: "45 Was sagt die Bezeichnung \"TLF 2000\"?",
antworten: ["a) Es handelt sich um ein Trockenlöschfahrzeug", "b) Es handelt sich um ein Tanklöschfahrzeug", "c) Das Fahrzeug hat eine Feuerlöschkreiselpumpe FPN 15/1000O", "d) Das Fahrzeug hat einen Motor mit 200 KW", ],
loesungen: ['b', ],
},
{frage: "46 Welche der nachfolgenden Feuerwehrfahrzeuge sind Löschfahrzeuge?",
antworten: ["a) Löschgruppenfahrzeug LF 20", "b) Tanklöschfahrzeug TLF 3000", "c) Löschgruppenfahrzeug LF 16TS", "d) Schlauchwagen SW 2000", "e) Gerätewagen-Gefahrgut", "f) Tragkraftspritzenfahrzeug TSF", ],
loesungen: ['a', 'b', 'c', 'f', ],
},
{frage: "47 Welche der nachfolgenden kraftbetriebenen Geräte können sich nach Norm als zusätzliche Beladung auf einem genormten Löschfahrzeug befinden?",
antworten: ["a) Tauchpumpe TP 4-1", "b) Tragbarer Stromerzeuger 5 kVA", "c) Brennschneidgerät", "d) Plasma-Schneidgerät", "e) Presslufthammer", "f) Motorkettensäge", "g) Hydraulisches Rettungsgerät", ],
loesungen: ['a', 'b', 'f', 'g', ],
},
{frage: "48 Was beinhaltet die Bezeichnung \"HLF 20\"?",
antworten: ["a) Löschgruppenfahrzeug", "b) Eingebauter Löschwasserbehälter mit einer nutzbaren Wassermenge von mindestens 1600 Liter vorhanden", "c) Schnellangriff Wasser vorhanden", "d) Feuerlöschkreiselpumpe FPN 10/1000 im Heck eingebaut", "e) Feuerlöschkreiselpumpe FPN 15/1000 als Frontpumpe angebaut", ],
loesungen: ['a', 'b', 'c', ],
},
{frage: "49 Was verstehen Sie unter dem Begriff \"Entlüftungszeit\"?",
antworten: ["a) Ein negativer Druck von - 0,8 bar muss in 30 Sekunden erreicht sein", "b) Erforderliche Zeit in Sekunden, um eine Pumpe einschließlich der Saugleitung zu entlüften und das Löschwasser mit positivem Druck bis zum Austrittsquerschnitt zu fördern.", "c) Er negative Druck darf von - 0,8 bar innerhalb einer Minute nicht mehr als 0,1 bar steigen", ],
loesungen: ['b', ],
},
{frage: "50 Warum benötigen Feuerlöschkreiselpumpen eine Entlüftungseinrichtung?",
antworten: ["a) Weil Ein- und Auslassventile nicht vorhanden sind", "b) Weil auch Schmutzwasser gefördert werden kann", "c) Weil die Drehzahl des Laufrades zu niedrig ist", "d) Weil der Luftdruck dem Wasserdruck entgegen wirkt", "e) Weil zwischen Laufrad und Pumpengehäuse kein luftdichter Abschluss ist", ],
loesungen: ['e', ],
},
{frage: "51 Welcher Zusammenhang besteht zwischen Saughöhe und Luftdruck?",
antworten: ["a) Hoher Luftdruck - hohe praktische Saughöhe", "b) Niederer Luftdruck ? hohe praktische Saughöhe", ],
loesungen: ['a', ],
},
{frage: "52 Welche Knoten, Schläge oder Stiche sind zum Aufbau einer Saugleitung nach den Richtlinien erforderlich?",
antworten: ["a) Mastwurf", "b) Pfahlstich", "c) Halbschlag", "d) Schotenstich", "e) Doppelschlinge", "f) Zimmermannschlag", ],
loesungen: ['a', 'c', 'f', ],
},
{frage: "53 Bei welcher Pumpe darf am Druckausgang beziehungsweise in der Druckleitung kein Absperrorgan angebracht werden?",
antworten: ["a) Wasserstrahlpumpe", "b) Turbinentauchpumpe", "c) Tauchpumpe mit elektrischem Antrieb", "d) Exzenterschneckenpumpe", "e) Feuerlöschkreiselpumpe", "f) Fass- und Behälterpumpe", ],
loesungen: ['d', ],
},
{frage: "54 Wovon hat sich der Maschinist zu überzeugen, bevor eine Einsatz- oder Unfallstelle verlassen wird?",
antworten: ["a) Brandwache bereitgestellt", "b) Hydranten entwässert", "c) Verkehrssicherungsgerät ins Fahrzeug zurück gebracht", "d) Feuerlöschkreiselpumpe entwässert", "e) Absperreinrichtungen geschlossen und Blindkupplungen aufgesetzt", "f) Löschgruppe vollzählig", ],
loesungen: ['c', 'd', 'e', ],
},
{frage: "55 Welche der folgenden Aussagen sind gemäß Unfallverhütungsvorschriften richtig?",
antworten: ["a) Der Fahrer eines Feuerwehrfahrzeuges hat erst dann anzufahren, wenn der Gruppenführer dazu das Zeichen gibt", "b) Während der Fahrt ist für die Einhaltung der Straßenverkehrsvorschriften allein der Fahrer verantwortlich", "c) Den sonstigen Straßenverkehr auf das abgestellte Feuerwehrfahrzeug aufmerksam machen", "d) Nie mit überladenem Fahrzeug fahren", "e) Keine Schnelligkeit auf Kosten der Sicherheit", "f) Zusätzliche Schutzkleidung beim Betrieb der Motorkettensäge, des Trennschleifers und der hydraulischen Rettungsgeräte tragen", "g) Wer Sonderrechte nach § 35 Straßenverkehrsordnung in Anspruch nimmt, ist zu erhöhter Aufmerksamkeit verpflichtet", ],
loesungen: ['a', 'b', 'c', 'd', 'e', 'f', 'g', ],
},
{frage: "56 Während des Betriebes einer Tragkraftspritze PFPN 10/1000 mit VW-Industriemotor leuchtet anfangs die grüne Kontrolllampe auf und erlischt nach kurzer Zeit. Welche Ursachen können vorliegen?",
antworten: ["a) Der Öldruck hat sich verringert", "b) Die Glühbirne ist durchgebrannt", "c) Der Keilriemen ist abgerissen", "d) Die Stromzuführung zur Glühbirne ist defekt", ],
loesungen: ['b', 'c', 'd', ],
},
{frage: "57 Welches sind Einflüsse, die verhindern, dass die theoretische Saughöhe von 10,33 Meter praktisch nicht erreicht werden kann?",
antworten: ["a) Niederer Barometerstand als normal", "b) Entlüftungseinrichtung erzeugt kein vollkommenes Vakuum", "c) Wassertemperatur ist höher als 4° CO", "d) In der Saugleitung oder Feuerlöschkreiselpumpe sind Undichtigkeiten", "e) Bei der saugseitigen Wasserförderung treten hydraulische Verluste (Strömungs- und Reibungsverluste)auf", "f) Die Feuerlöschkreiselpumpe erreicht keine Nenndrehzahl mehr", ],
loesungen: ['a', 'b', 'c', 'd', 'e', ],
},
{frage: "58 Wie kann sich der Maschinist helfen, wenn die Entlüftungseinrichtung der Feuerlöschkreiselpumpe ausgefallen ist?",
antworten: ["a) Bei Tanklöschfahrzeugen Feuerlöschkreiselpumpe und Saugleitung aus dem eingebauten Löschwasserbehälter füllen", "b) Gruppenführer benachrichtigen, damit eine Feuerlöschkreiselpumpe nachgefordert wird", "c) Pumpe und Saugleitung \"von Hand\" auffüllen", ],
loesungen: ['a', 'b', 'c', ],
},
{frage: "59 Worauf hat der Maschinist im Winter bei einer Flüssigkeitsring-Entlüftungseinrichtung zu achten?",
antworten: ["a) Dass die Feuerlöschkreiselpumpe nur im beheizten Feuerwehrhaus abgestellt wird", "b) Dass die Feuerlöschkreiselpumpe samt Entlüftungseinrichtung nach jedem Einsatz und jeder Übung entleert   wird", "c) Dass die Entlüftungseinrichtung mit Frostschutzmittel aufgefüllt wird", ],
loesungen: ['b', 'c', ],
},
{frage: "60 Wer ist bei einer Einsatzfahrt für das Feuerwehrfahrzeug verantwortlich?",
antworten: ["a) Der Maschinist als Fahrer des Feuerwehrfahrzeuges", "b) Der Gruppenführer", "c) Der Zugführer", ],
loesungen: ['a', ],
},
];